databases:
  - name: mc-top10growth

services:
  # worker: ETL running every minute
  - type: worker
    name: etl-top10growth
    env: python
    startCommand: python etl.py
    schedule: "* * * * *"

  # web: FastAPI service
  - type: web
    name: api-top10growth
    env: python
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT

staticSites:
  # React UI
  - name: ui-top10growth
    env: node
    buildCommand: npm install && npm run build
    publishDir: dist