databases:
  - name: mc-top10growth

services:
  - type: worker
    name: etl
    env: python
    startCommand: python etl.py
    schedule: "0 * * * *"   # every hour on the hour

  # web: FastAPI service
  - type: web
    name: api-top10growth
    env: python
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT

staticSites:
  # React UI
  - name: ui-top10growth
    env: node
    buildCommand: npm install && npm run build
    publishDir: dist