# render.yaml (at repo root)

databases:
  - name: mc-top10growth

services:
  - type: worker
    name: etl
    env: python
    startCommand: python etl.py
    schedule: "0 * * * *"        # every hour on the hour

  - type: web
    name: api-top10growth
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT